{% set name = "python-chromedriver-binary" %}
{% set version = "2.39.0" %}
{% set sha256 = "e11cf863e489690740e0b33416e1bbd84dddfca44c37527882d7619f05c9a554" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - setuptools
    - pandoc
  run:
    - python

test:
  requires:
    - setuptools
  imports:
    - chromedriver_binary
  commands:
    - chromedriver-path

about:
  home: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Downloads and installs the chromedriver binary version'
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows 
    operating systems.

extra:
  recipe-maintainers:
    - igortg
    - williamjamir
