{% set name = "python-chromedriver-binary" %}
{% set version = "119.0.6045.105.0" %}
{% set chromedriver_version = version[:-2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 18fdad371953e9daa5fa577d54e7b236f61f7693c749405a17df9613af4286c0
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip  # [linux]
    sha256: a7787ef8b139170cab4abfca4a0284fd5d006bfd979624b4af25b64d583a6f44  # [linux]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_mac64.zip  # [osx]
    sha256: 6abdc9d358c2bc4668bef7b23048de2a9dbd3ad82cfbc6dfe322e74d4cff1650  # [osx]
  - url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/{{ chromedriver_version }}/win32/chrome-win32.zip  # [win]
    sha256: 7a6b4694afdb735468694d0ecaab173e095d76e226dca85f4f528364a1d6cb3f  # [win]

build:
  number: 0
  script:
    - chmod +x chromedriver  # [unix]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
  entry_points:
    - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path
  binary_relocation: false  # [osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - chromedriver_binary
  commands:
    - chromedriver-path
    # TODO: investigate on linux, (at least) libxcb is missing... 
    - $(chromedriver-path)/chromedriver --version  # [osx]

about:
  home: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Downloads and installs the chromedriver binary version
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - igortg
    - williamjamir
    - bollwyvl
