{% set name = "python-chromedriver-binary" %}
{% set version = "77.0.3865.40.0" %}
{% set chromedriver_version = version[:-2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 879bdeef8a162bf1c6e076fe038685853c9a270265b882e842ac096a3640ca22
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip  # [linux]
    sha256: c5aefc828c62fcfeaae0dfbb448026fcfca5477c91b0e984f6f54d92abd76235  # [linux]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_mac64.zip  # [osx]
    sha256: 6fd7ad8944f762933e2a62aa1908de26c94a81f5cb6673446700794ae0574313  # [osx]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_win32.zip  # [win]
    sha256: 767d8f9b062ac784671cc0b37dda4d66cdb08419020ade84669b2217643b4949  # [win]

build:
  number: 0
  script:
    - chmod +x chromedriver  # [unix]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"
  entry_points:
    - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - chromedriver_binary
  commands:
    - chromedriver-path

about:
  home: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Downloads and installs the chromedriver binary version'
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - igortg
    - williamjamir
    - bollwyvl
