{% set name = "python-chromedriver-binary" %}
{% set version = "76.0.3809.68.0" %}
{% set chromedriver_version = version[:-2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 3bf866402fdadb8b99ce7c0bcec5b1e8ad4d03099817e73ed6dfb7da2e87fadd
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip  # [linux]
    sha256: fb2f6dd9bd828a6fc40b7387e839caa72faeecd72cf7a1c6b6b5ab760a348b13  # [linux]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_mac64.zip  # [osx]
    sha256: 093ce5480be24520c1b5c0d265cc20a3b28527877d0bb02fe24ab5ac503d1239  # [osx]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_win32.zip  # [win]
    sha256: a27d56f663326a6c742ae647f931224b70c84ba74b3f3a4b9e35628892cc7b1a  # [win]

build:
  number: 0
  script:
    - chmod +x chromedriver  # [unix]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"
  entry_points:
    - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - chromedriver_binary
  commands:
    - chromedriver-path

about:
  home: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Downloads and installs the chromedriver binary version'
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - igortg
    - williamjamir
    - bollwyvl
