{% set name = "python-chromedriver-binary" %}
{% set version = "110.0.5481.30.0" %}
{% set chromedriver_version = version[:-2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 067c906f839328a3cc44ab602dbe212935b10f7ab752c6b327ccdc18c6f4e2fb
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip  # [linux]
    sha256: bc5af03f72ed19a20c3945b0ed85db344ed27658a832788caf8f42e5a1424222  # [linux]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_mac64.zip  # [osx]
    sha256: c476ed24f76b23da77726a3800c5d8ea8cbc6e9f8e61ed4ddbbe8497a2039876  # [osx]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_win32.zip  # [win]
    sha256: 7ce1f0417a7c84ed1370a4b2c2e2b6a5205059aabfce22b7fc924414eafb0cc1  # [win]

build:
  number: 0
  script:
    - chmod +x chromedriver  # [unix]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
  entry_points:
    - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path
  binary_relocation: false  # [osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - chromedriver_binary
  commands:
    - chromedriver-path
    # TODO: investigate on linux, (at least) libxcb is missing... 
    - $(chromedriver-path)/chromedriver --version  # [osx]

about:
  home: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Downloads and installs the chromedriver binary version
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - igortg
    - williamjamir
    - bollwyvl
