{% set name = "python-chromedriver-binary" %}
{% set version = "2.44.0" %}
{% set sha256 = "13c750017a8d618709b0e1b49f7e23f555255ad0fb726788725804e22ac530e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000

requirements:
  host:
    - python
    - pip
    - setuptools
    - pandoc
  run:
    - python

test:
  requires:
    - setuptools
  imports:
    - chromedriver_binary
  commands:
    - chromedriver-path

about:
  home: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Downloads and installs the chromedriver binary version'
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows 
    operating systems.

extra:
  recipe-maintainers:
    - igortg
    - williamjamir
