{% set name = "python-chromedriver-binary" %}
{% set version = "95.0.4638.17.0" %}
{% set chromedriver_version = version[:-2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: e6386b86d627bce3d4f12e729ea40e0817f1b2ec26cc799cee3203b0a424f826
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip  # [linux]
    sha256: 58c0e2d3647a5adddc4992ed356d8ee48f45327b4970325fc2cc2a990714184b  # [linux]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_mac64.zip  # [osx]
    sha256: 88821a2f7eade0d6489d10b1aa90684e8b7511900709f2a42d7fe08e441c876e  # [osx]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_win32.zip  # [win]
    sha256: 511b424a60ee996f8dfc2a1354e2c7a09a0325aed456469ce6451497888f9fa4  # [win]

build:
  number: 0
  script:
    - chmod +x chromedriver  # [unix]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
  entry_points:
    - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - chromedriver_binary
  commands:
    - chromedriver-path

about:
  home: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Downloads and installs the chromedriver binary version
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - igortg
    - williamjamir
    - bollwyvl
