{% set name = "python-chromedriver-binary" %}
{% set version = "105.0.5195.52.0" %}
{% set chromedriver_version = version[:-2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 75a0dbd3b1f9f51a565ae3c187d527ff6eb7f3bb3c4c0f36a98ba61c51243082
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip  # [linux]
    sha256: c41cc88ac6c7b6e5c48b7ca629d48bf594903862a3d30cdeb35a97d48c397318  # [linux]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_mac64.zip  # [osx]
    sha256: c0e2982c36f02216a4eaaaff2672b6aa702bbc2b904b00e4ca736c708b784867  # [osx]
  - url: https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_win32.zip  # [win]
    sha256: 32af1c0764655069e16b85afe0b9eb1ba8a4870a872b5c8407010df4cc6c52ba  # [win]

build:
  number: 0
  script:
    - chmod +x chromedriver  # [unix]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
  entry_points:
    - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path
  binary_relocation: false  # [osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - chromedriver_binary
  commands:
    - chromedriver-path
    # TODO: investigate on linux, (at least) libxcb is missing... 
    - $(chromedriver-path)/chromedriver --version  # [osx]

about:
  home: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Downloads and installs the chromedriver binary version
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - igortg
    - williamjamir
    - bollwyvl
