travis:
  secure:
    BINSTAR_TOKEN: Ut14YqkOixuJBir9G6z1+PYYGkCbzIY/a8BWfM4XzFXQGrkQuYUwC4t8Z9mK9wR2PAvUY8/i6X4OPGsAjfQaOuiMEJE7DGAHJ2jWlUXa2ukBhc8ntt2cw05RSqQ2saUoc3HvIeWXCi/0qiCS+cN9chCxA5YCMjcfe4qbPDY7uE6z/PoDrNARF7XWQD2fi105CUgCq4OxQ+MSFCT3RfhuewgTqLLh1pBDyx0JTeCwpg2gXIkd2/3t/vzID8CXXNV2VGhVXwISA+/peMXaP/Df5Ry9ECBWCgdfknzlLCNgARnmLAA1s/iCruHXMsKIWuyyvbyxdHscKlVTST/Wv8WGWUoMc7W5gGyOuDrP8HKnnJgP7w89Y0mSWfhAgpUigGZ5xmXE02pbX3hKHrQu39ftZ/niHaYAstBEwRxFVgcag0LXMmfi65cNU2wrlK6ep0wN58aUFHWxiRWxWN/4hlLUGRnj+G6GFQLsdwDxvMpQvY3ZXKi0JlPoQ6xEcrWgfXqj6jtL3bLOUPrTUKULUrGuB9ssIDI/TqgvRemS1wohLQ7HIn1DUXjg3/FnHZnKA8AaCMWWkbi6dYmI06xxhrDmkAqYcqQeT+nCB1hWp5CAioLjwl13z1A/XxfjISEY7BpitCObCsN4gE7MIm8gUi5QIryWCFshvq+NW80aWDNFk68=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
